include:
  - template: Jobs/Code-Quality.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/Code-Quality.gitlab-ci.yml
  - template: Jobs/Code-Intelligence.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/Code-Intelligence.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Security/Secret-Detection.gitlab-ci.yml

variables:
  SECRET_DETECTION_EXCLUDED_PATHS: "node_modules/*"
  SAST_EXCLUDED_PATHS: "node_modules/*"

cache:
  paths:
    - node_modules/

.node_template:
  image: node:18
  before_script:
    - npm install
  script:
    - npm run build

test:lint:
  extends: .node_template
  script:
    - npm run lint

test:vulnerabilities prod:
  extends: .node_template
  script:
    - npm audit --production
  only:
    - master
    - tags
  allow_failure: false

test:vulnerabilities dev:
  extends: .node_template
  script:
    - npm audit
  except:
    - master
    - tags
  allow_failure: true

test:node:16:
   image: node:16
   extends: .node_template

test:node:18:
  extends: .node_template

test:node:19:
  image: node:19
  extends: .node_template

test:node:20:
  image: node:20
  extends: .node_template

# Publish tagged versions to npm
publish:
  extends: .node_template
  stage: deploy
  only:
    - tags
  script:
    - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish